"""Inicializacion de la base de datos

Revision ID: 46df6427f746
Revises:
Create Date: 2025-12-07 23:42:51.698665

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "46df6427f746"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role_x_permission",
        sa.Column("id_role", sa.Integer(), nullable=False),
        sa.Column("id_permission", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_permission"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_role"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id_role", "id_permission"),
    )
    op.create_table(
        "user",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("id_role", sa.Integer(), nullable=False),
        sa.Column("external_reference", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_role"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_reference"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "contract",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("percentaje", sa.Float(), nullable=False),
        sa.Column("referer_id_user", sa.UUID(), nullable=False),
        sa.Column("referred_id_user", sa.UUID(), nullable=False),
        sa.Column(
            "valid_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(
            ["referer_id_user"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referred_id_user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("""
        INSERT INTO role (name, is_active)
        VALUES
            ('administrator', TRUE),
            ('teacher', TRUE)
        """)
    op.execute("""
        INSERT INTO permission (name, is_active)
        VALUES
            ('create_user', TRUE),
            ('update_user', TRUE),
            ('delete_user', TRUE),
            ('read_users', TRUE),
            ('read_all_courses', TRUE),
            ('read_courses', TRUE),
            ('read_all_lessons', TRUE),
            ('read_lessons', TRUE),
            ('read_sales', TRUE),
            ('read_all_students', TRUE),
            ('read_students', TRUE),
            ('read_external_users', TRUE)
        """)
    op.execute("""
        INSERT INTO role_x_permission (id_role, id_permission, is_active)
        SELECT r.id, p.id, TRUE
        FROM role r, permission p
        WHERE r.name = 'administrator'
        """)
    op.execute("""
        INSERT INTO role_x_permission (id_role, id_permission, is_active)
        SELECT r.id, p.id, TRUE
        FROM role r
        JOIN permission p ON p.name IN ('read_courses', 'read_lessons','read_sales','read_students')
        WHERE r.name = 'teacher'
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("role_x_permission")
    op.drop_table("role")
    op.drop_table("permission")
    # ### end Alembic commands ###
