"""Se agrega tabla password_reset_token

Revision ID: 5961238f66fa
Revises: 46df6427f746
Create Date: 2026-01-22 20:05:39.911237

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5961238f66fa"
down_revision: Union[str, Sequence[str], None] = "46df6427f746"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_table(
        "password_reset_token",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("id_user", sa.UUID(), nullable=False),
        sa.Column("expired_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_table("password_reset_token")
    # ### end Alembic commands ###
